# Generated by Django 4.2.5 on 2023-09-10 11:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='bio',
        ),
        migrations.AddField(
            model_name='staff',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='dob',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
