# Generated by Django 4.2.5 on 2023-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial_app', '0002_remove_staff_bio_staff_desc_staff_dob_staff_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
